/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AgentMemory {
  constructor(path: string)
  store(content: string, metadataJson?: string | undefined | null, dedupThreshold?: number | undefined | null, noEmbed?: boolean | undefined | null): StoreResult
  search(options: SearchOptions): Array<MemoryRecord>
  get(idOrPrefix: string): MemoryRecord | null
  update(idOrPrefix: string, content?: string | undefined | null, metadataJson?: string | undefined | null, mergeMetadata?: boolean | undefined | null): void
  delete(idOrPrefix: string): void
  list(options?: ListOptions | undefined | null): Array<MemoryRecord>
  related(idOrPrefix: string, limit?: number | undefined | null): Array<MemoryRecord>
  stats(): MemoryStats
  vacuum(): void
}

export interface ListOptions {
  memoryType?: string
  sort?: string
  limit?: number
  offset?: number
  before?: number
  after?: number
}

export interface MemoryRecord {
  id: string
  content: string
  vector?: Array<number>
  metadataJson?: string
  createdAt: number
  updatedAt: number
  lastAccessed: number
  accessCount: number
  score?: number
}

export interface MemoryStats {
  count: number
  embedded: number
  typeDistributionJson: string
}

export interface SearchOptions {
  text?: string
  vector?: Array<number>
  metadataFilterJson?: string
  limit?: number
  textOnly?: boolean
  before?: number
  after?: number
}

export interface StoreResult {
  id: string
  deduplicated: boolean
}
