[workspace]
members = [
  "crates/ironclawd",
  "crates/irowclaw",
  "crates/common",
  "crates/security",
  "crates/tools",
  "crates/memory",
  "crates/channels",
  "crates/heartbeat",
  "crates/ironclaw-cli",
  "crates/farm",
]
exclude = ["core-agent-memory"]
resolver = "2"

[workspace.package]
version = "0.10.0"
edition = "2021"
license = "unlicense"
