[package]
name = "ironclaw-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ironclaw"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
futures = "*"
mime_guess = "*"
prost = "*"
serde_json = "*"
tokio = { version = "*", features = [
  "io-std",
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
] }
tokio-tungstenite = "*"
